# -*- coding: utf-8 -*-
"""DataAnalysis_ElectricVehicles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IZluGjST-g406fcuba5vIkrgK7rjw2uS

# About
authors: Shahar and Shlomi

[Github](https://github.com/shachar700/DataAnalysis_ElectricVehicles)

Column Name -	Description

VIN (1-10) - First 10 characters of the Vehicle Identification Number.

County - The county where the vehicle is registered or located.

City - The city where the vehicle is registered or located.

State - The U.S. state abbreviation (e.g., WA for Washington).

Postal Code - ZIP/postal code of the vehicle's location.

Model Year - The year the vehicle was manufactured.

Make - The manufacturer (e.g., Tesla, Nissan).

Model - The specific model of the car (e.g., Model 3, Leaf).

Electric Vehicle Type - Type of EV (Battery Electric Vehicle (BEV), Plug-in Hybrid Electric Vehicle (PHEV), etc.).

Clean Alternative Fuel Vehicle (CAFV) Eligibility - Indicates whether the vehicle qualifies under CAFV rules.

Electric Range - How many miles the vehicle can travel on electricity alone.

Base MSRP - Manufacturer's Suggested Retail Price at base level (starting price).

Legislative District - Legislative district associated with the vehicle's location.

DOL Vehicle ID - Department of Licensing Vehicle ID (state-assigned).

Vehicle Location - More detailed info about where the vehicle is located.

Electric Utility - The electric company servicing that area.

2020 Census Tract - Census tract identifier from the 2020 census (used for demographic/geographic analysis).

Questions:
- Vehicles per state
- Vehicles per county
- Vehicles per city
- Vehicles per legistrative district (handle na values)
- Vehicles per electric utility
- Top 7 companies with total amount of vehicles
- Top 7 models with total amount of vehicles
- Popular companies in each county
- Popular models in each county
- Electric Range per model (handle na values)

handle missing values: use Linear Regression/KNN to predict electric range,

split categories and turn them to binary values
dummies for Electric Utility and handle

# Installs

# Libraries
"""

import requests
import pandas as pd
import numpy as np

"""# Pre-process"""

electric_vehicles_url = "https://raw.githubusercontent.com/shachar700/DataAnalysis_ElectricVehicles/refs/heads/main/data/Electric_Vehicle_Population_Data.csv"

def download_file(url, file_name):
  response = requests.get(url)
  if response.status_code == 200:
    with open(file_name, "wb") as file:
        file.write(response.content)
    print(f"Downloaded: {file_name}")

download_file(electric_vehicles_url, "electric_vehicles.csv")

df = pd.read_csv("/content/electric_vehicles.csv")
df.head(5)

df.info()

df.describe()

df = df.drop(columns=["Base MSRP", "Vehicle Location", "DOL Vehicle ID", "2020 Census Tract"])

#print(f"{df.isna().any(axis=1).sum()} rows")
display(df[df["County"].isna()])
df = df.dropna(subset=["County"])
df.loc[df["Electric Range"] == 0.0, "Electric Range"] = np.nan
display(df.isnull().sum())
df.head(3)

df['Make'].value_counts()

df[['Make','Model']].value_counts()